#ifndef FILE_SYSTEM_ERROR_
#define FILE_SYSTEM_ERROR_

#define NO_FILE_NAME -100
#define NO_FILE_DATA -101
#define FILE_NAME_TOO_LONG -102
#define DATA_TO_LONG -103
#define TOO_MANY_FILES_OPEN -104



#endif

